<a id='home'></a>
### purpose

estimate fitness of individuals in the common garden on the spatially continuous simulation landscape

### outline
1. [get environmental data for each garden](#envdata)
1. [estimate fitness in each common garden](#fit)

In [1]:
from pythonimports import *

import runtime_API as rt  # contains fitness_calculator.R

outerdir = '/work/lotterhos/brandon/continuous_space_runtime'

# continuous space sims directory
tdir = '/home/b.lind/offsets/run_20220919_tutorial/tutorial'

# directories with files
training_dir = f'{outerdir}/gradient_forests/training/training_files'
fitting_dir = f'{outerdir}/gradient_forests/fitting'
garden_dir = f'{fitting_dir}/garden_files'

# where to save files
fitness_dir = makedir(f'{outerdir}/fitness_mats')

# parallel engines
lview, dview = get_client(cluster_id='1733328168-jy14', profile='lotterhos')

t0 = dt.now()  # notebook timer

rt.latest_commit()
session_info.show()

36 36
#########################################################
Today:	December 04, 2024 - 12:40:37 EST
python version: 3.8.5
conda env: mvp_env

Current commit of pythonimports:
commit 6a767410e7b569adbf9df526de108f22ef50aad8
Author: Brandon Lind <lind.brandon.m@gmail.com>
Date:   Wed Mar 6 13:42:13 2024 -0700

Current commit of MVP_offsets:
commit 5ce82f4d655645237a0f4026fa32e220226dc373
Author: Brandon Lind <lind.brandon.m@gmail.com>
Date:   Thu May 16 13:02:58 2024 -0400

Current commit of MVP_runtime:
commit a98ef38f88b81d808c334e87d0c6392e142941da
Merge: 50cf2c9 cc54cc3
Author: Brandon Lind <lind.brandon.m@gmail.com>
#########################################################

<a id='envdata'></a>
# get environmental data for each garden

[top](#home)

In [2]:
garden_files = fs(garden_dir)

print(len(garden_files))

garden_files[0]

100

'/work/lotterhos/brandon/continuous_space_runtime/gradient_forests/fitting/garden_files/tutorial_GF_gardenfile_1.txt'

In [3]:
# note each column has one value, so I can use the first row when calculating fitness to a specific garden
    # see calc_R_fitness calls
pd.read_table(garden_files[0], index_col=0)

         env1_mat  env2_MTWetQ  env3_MTDQ  env4_PDM  env5_PwarmQ  env6_PWM
25_33    0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
85_34    0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
57_44    0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
31_45    0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
11_46    0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
...           ...          ...        ...       ...          ...       ...
22_8575  0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
75_8580  0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
62_8582  0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
79_8585  0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569
78_8590  0.186225    -0.226935   0.861531  0.221974    -0.363974  0.761569

[1000 rows x 6 columns]

In [4]:
garden_data = {}
for f in pbar(garden_files):
    garden_ID = op.basename(f).split('.')[0].split("_")[-1]
    garden_data[garden_ID] = pd.read_table(f, index_col=0)
    
garden_data[garden_ID]

100%|███████████████| 100/100 [00:00<00:00, 226.52it/s]

         env1_mat  env2_MTWetQ  env3_MTDQ  env4_PDM  env5_PwarmQ  env6_PWM
25_33    0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
85_34    0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
57_44    0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
31_45    0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
11_46    0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
...           ...          ...        ...       ...          ...       ...
22_8575  0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
75_8580  0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
62_8582  0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
79_8585  0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201
78_8590  0.034177     0.399089  -0.440848 -0.464035     0.673533  0.360201

[1000 rows x 6 columns]

In [5]:
garden_data[garden_ID].iloc[0]

env1_mat       0.034177
env2_MTWetQ    0.399089
env3_MTDQ     -0.440848
env4_PDM      -0.464035
env5_PwarmQ    0.673533
env6_PWM       0.360201
Name: 25_33, dtype: float64

<a id='fit'></a>
# estimate fitness in each common garden

[top](#home)

In [6]:
# look at phenodata read in by fitness_calculator.R
phenodata = pd.read_table(
    '/work/lotterhos/brandon/continuous_space_runtime/individual_data.txt',
)

traits = ["phenotype1_mat",  # list copied from fitness_calculator.R
           "phenotype2_MTWetQ",
           "phenotype3_MTDQ",
           "phenotype4_PDM",
           "phenotype5_PwarmQ",
           "phenotype6_PWM"]

phenodata[traits]

,phenotype1_mat,phenotype2_MTWetQ,phenotype3_MTDQ,phenotype4_PDM,phenotype5_PwarmQ,phenotype6_PWM
0,0.737967,-0.191421,0.142992,-0.131894,-0.452497,-0.541651
1,-0.274081,-0.428332,-0.012880,0.221058,0.229296,0.066597
2,-0.676326,0.086629,-0.470671,0.218813,0.260098,-0.103465
3,-0.283221,-0.403942,-0.333718,-0.200554,-0.345915,-0.410001
4,0.057616,-0.303201,0.731600,0.195679,-0.367110,0.196296
...,...,...,...,...,...,...
995,-0.070241,-0.367056,-0.061876,-0.308041,-0.468111,-0.508108
996,-0.050435,-0.342693,0.128758,0.107181,-0.061796,-0.081682
997,0.354088,0.493751,0.064744,-0.243331,-0.164916,-0.244379
998,-0.009027,0.424444,-0.575177,-0.514613,0.586778,0.266235
999,-0.556467,0.160341,-0.441661,-0.142595,0.401628,0.117506

In [7]:
def calc_R_fitness(*args):
    import subprocess
    
    args = [str(arg) for arg in args]
    
    Rscript = '/home/b.lind/anaconda3/envs/MVP_env_R4.0.3/bin/Rscript'
    script_file = '/home/b.lind/code/06_run_time_project/07_continuous_space_sims/fitness_calculator.R'
    
    output = subprocess.check_output(
        [
            Rscript,
            script_file,
            *args
        ]
    )

    return output

In [8]:
fitness_dir

'/work/lotterhos/brandon/continuous_space_runtime/fitness_mats'

In [9]:
jobs = []

for gardenID, data in garden_data.items():
    (opt0, opt1, opt2, opt3, opt4, opt5) = data.iloc[0]

    output_file = op.join(fitness_dir, f'tutorial_{gardenID}.txt')

    jobs.append(
        lview.apply_async(
            calc_R_fitness, *('tutorial',
                              output_file, 
                              opt0, opt1, opt2, opt3, opt4, opt5)
        )
    )

watch_async(jobs)

Watching 100 jobs ...

100%|███████████████| 100/100 [00:04<00:00, 22.46it/s]

In [10]:
fitness_dir

'/work/lotterhos/brandon/continuous_space_runtime/fitness_mats'

In [11]:
print(jobs[0].r.decode('utf-8'))

R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /work/lotterhos/brandon/anaconda3/envs/MVP_env_R4.0.3/lib/libopenblasp-r0.3.17.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] progress_1.2.2 mvtnorm_1.1-3

loaded via a namespace (and not attached):
 [1] compiler_4.0.3    ellipsis_0.3.2    R6_2.5.1          cli_3.3.0
 [5] hms_1.1.1         prettyunits_1.1.1 crayon_1.5.1      vctrs_0.4.1
 [9] lifecycle_1.0.1   pkgconfig_2.0.3   rlang_1.0.2
[1] "dim(phenos) = " "1000"           "6"
         phenotype1_mat phenotype2_MTWetQ phenotype3_MTDQ phenotype4_PDM
25_33       0.737967000       -0.19142100     0.142992000   -0.131894000
85_34      -0.274081000       -0.42833200    -0.012880000    0.221058000
57_44      -0.676326000        0.08662870    -0.470671000    0.218813000
31_45      -0.283221000       -0.40394200    -0.333718000   -0.200554000
11_46       0.057616300       -0.30320100     0.731600000    0.195679000
22_64       0.265628000       -0.23187300     0.214004000   -0.239776000
47_65      -0.421039000       -0.41233700    -0.109637000    0.609752000
10_72       0.227355000       -0.37825000     0.035228400    0.075940800
20_85      -0.456489000       -0.06604580    -0.341581000    0.132091000
64_106     -0.013052500       -0.50985400     0.111542000    0.465314000
100_119     0.031087100        0.44368400    -0.588170000   -0.521467000
76_127     -0.443200000        0.23119600    -0.419060000    0.080250200
11_132     -0.019120400       -0.27036100     0.065056800   -0.071495000
23_164      0.510602000       -0.17757300     0.231440000   -0.419965000
18_173     -0.269870000       -0.40202900     0.720072000    0.376167000
29_175     -0.335275000        0.14417900    -0.397329000    0.065389200
49_194     -0.377749000        0.20743000    -0.413994000    0.137115000
67_198     -0.184158000       -0.41754300     0.109284000    0.177576000
6_207       0.193647000       -0.32085200    -0.094090400    0.207359000
61_215      0.230910000        0.34698600     0.031809600   -0.246252000
22_216      0.314260000       -0.29617200     0.238027000   -0.217692000
47_221     -0.130767000       -0.39121500     0.114193000    0.387924000
29_224     -0.237854000        0.23553000    -0.285837000    0.107935000
22_230      0.314260000       -0.29617200     0.238027000   -0.217692000
9_236      -0.269870000       -0.40202900     0.720072000    0.376167000
67_254     -0.429696000        0.25325200    -0.305009000    0.278879000
52_255      0.351935000        0.46728800     0.049409800   -0.464458000
64_261      0.170500000       -0.23696700     0.246031000    0.261601000
30_268     -0.519606000        0.03721010    -0.355127000    0.083247700
42_269      0.436167000        0.51715100     0.023937900   -0.459102000
1_271       0.153022000       -0.18253600     0.685965000    0.280610000
96_280     -0.056418500        0.33551200    -0.123932000   -0.121835000
84_293     -0.161239000       -0.42732700     0.026063000    0.479783000
19_306     -0.419400000       -0.51282800    -0.455720000    0.463826000
78_309     -0.498719000        0.16499400    -0.571349000   -0.097083800
77_314     -0.454260000        0.25522700    -0.394919000    0.110971000
34_338      0.097412000       -0.19079400    -0.198010000   -0.012061200
92_348      0.160247000        0.38640000     0.002166150    0.101997000
66_352     -0.201075000       -0.44183800     0.051344200    0.122645000
63_359     -0.232044000       -0.45188500     0.100680000    0.433829000
66_382     -0.201075000       -0.44183800     0.051344200    0.122645000
79_385     -0.197633000        0.25075700    -0.218747000   -0.307916000
40_386     -0.582723000        0.14046600    -0.368673000    0.034404800
51_397      0.186628000        0.42722500    -0.049467900   -0.534821000
50_404     -0.582723000        0.14046600    -0.368673000    0.034404800
36_405      0.071670200       -0.37014000     0.203927000    0.450454000
15_412      0.231697000       -0.43329200    -0.056751100   -0.117897000
16_423      0.561615000       -0.26037700     0.375563000    0.169497000
26_437     -0.004361510       -0.34910500     0.151848000    0.204275000
54_438      0.316408000       -0.37567100     0.104927000   -0.050147100
18_449      0.036953500       -0.38069600     0.092179500    0.489566000
64_450     -0.246439000       -0.33463400     0.095144700    0.446224000
48_452     -0.225588000       -0.27834000    -0.082695600    0.154422000
54_465      0.390058000       -0.24003100     0.183304000   -0.099372200
72_469      0.288359000        0.41089900     0.018007000   -0.288328000
34_479      0.233554000       -0.19104500    -0.054761600   -0.160458000
57_480      0.345626000       -0.36081200     0.318694000    0.282803000
91_481      0.248818000        0.53749900    -0.064993500   -0.252246000
30_487     -0.328370000        0.17171000    -0.257711000   -0.020330800
45_502      0.143960000       -0.20635800     0.250297000    0.162685000
28_505     -0.077769500       -0.38743600     0.024585300    0.511847000
45_518      0.199531000       -0.36133700     0.170674000    0.085399400
98_519      0.077684900        0.39753300    -0.140338000   -0.336142000
66_520     -0.443200000        0.23119600    -0.419060000    0.080250200
95_525     -0.412786000        0.14537100    -0.337522000    0.117701000
73_530      0.399555000       -0.19288700     0.278741000    0.249292000
92_531      0.012603400       -0.33572200     0.115990000    0.419220000
53_537      0.321043000        0.47444800     0.165565000   -0.177605000
35_554      0.256685000       -0.27841800     0.166750000   -0.039979500
76_569     -0.330607000       -0.29758700    -0.013541500    0.227338000
37_572     -0.002729260       -0.32197700     0.169589000    0.674385000
3_573       0.616887000       -0.27057500     0.144386000   -0.257021000
98_582      0.066011900        0.38934000    -0.094765100   -0.367076000
32_607      0.406505000        0.41475100     0.034619000   -0.373919000
73_629      0.165869000        0.23733700    -0.062286900    0.144519000
36_641      0.194818000       -0.28992600     0.378403000    0.660035000
5_644       0.579294000       -0.20327600     0.130443000   -0.124323000
55_649      0.237352000       -0.21339300     0.229930000    0.195905000
8_652      -0.123582000       -0.30668000     0.731776000    0.461790000
30_665     -0.343847000        0.26766700    -0.348745000    0.048445200
59_670     -0.424463000        0.20665000    -0.459590000   -0.101109000
82_671      0.283024000        0.32600300     0.166446000    0.076847900
47_678     -0.130767000       -0.39121500     0.114193000    0.387924000
93_681     -0.161239000       -0.42732700     0.026063000    0.479783000
75_688     -0.162567000       -0.43123100     0.064028900    0.228411000
11_692     -0.151590000       -0.33871100     0.036645900   -0.063271400
22_695      0.070611500       -0.34663400     0.034932900   -0.213321000
85_705     -0.304552000       -0.35465700    -0.075920200    0.302045000
60_725     -0.365127000        0.33568400    -0.321792000   -0.298729000
29_733      0.049574300       -0.26410500    -0.113128000   -0.022446800
81_740     -0.055510300        0.41239200    -0.141998000   -0.343650000
89_753     -0.073995800        0.40658800    -0.249334000   -0.345439000
50_766     -0.582723000        0.14046600    -0.368673000    0.034404800
79_780     -0.077175100        0.33278000    -0.542456000   -0.545458000
84_797     -0.347087000       -0.41482600    -0.077104100    0.319471000
89_808     -0.097662100        0.36342700    -0.121072000   -0.435369000
61_815      0.148446000        0.34436700    -0.012923100   -0.360738000
33_816      0.406505000        0.41475100     0.034619000   -0.373919000
74_845     -0.198004000       -0.46368000    -0.046316400    0.511616000
21_855     -0.115205000       -0.27632500    -0.023083300   -0.032464900
2_857       0.057616300       -0.30320100     0.731600000    0.195679000
29_861      0.033359500       -0.25554100    -0.105148000    0.005720630
84_874     -0.161239000       -0.42732700     0.026063000    0.479783000
37_885     -0.479389000       -0.49831600    -0.259334000    0.455564000
37_886     -0.194189000       -0.38324600     0.084996900    0.609163000
1_891       0.163337000       -0.21220600     0.767262000    0.243419000
23_897      0.352482000       -0.22707800     0.062598700   -0.327387000
83_901     -0.061525600       -0.34178600    -0.011406100    0.533827000
37_907     -0.358973000       -0.44752800    -0.094085900    0.704610000
22_911     -0.151590000       -0.33871100     0.036645900   -0.063271400
48_915     -0.211477000       -0.32432400    -0.046285700    0.285036000
6_925       0.193647000       -0.32085200    -0.094090400    0.207359000
9_935      -0.247512000       -0.40421000     0.655439000    0.398094000
27_946     -0.043306400       -0.34924900     0.052079500    0.550982000
98_957      0.066011900        0.38934000    -0.094765100   -0.367076000
17_980     -0.153308000       -0.30433700     0.102494000    0.560736000
75_982     -0.235573000       -0.41772500    -0.000195193    0.326824000
16_996      0.561615000       -0.26037700     0.375563000    0.169497000
80_1016    -0.136166000        0.27281800    -0.536960000   -0.469055000
87_1026    -0.361888000        0.26751100    -0.439242000   -0.140803000
13_1036     0.291626000       -0.40518000    -0.058197900   -0.190642000
4_1066      0.206082000        0.42162300     0.089773200   -0.487325000
14_1078     0.319129000        0.02365330     0.109029000   -0.511848000
86_1093    -0.443200000        0.23119600    -0.419060000    0.080250200
9_1098      0.227355000       -0.37825000     0.035228400    0.075940800
10_1100    -0.217923000        0.00671911     0.429013000    0.197913000
54_1102     0.217734000       -0.22440100     0.290466000    0.210342000
79_1111    -0.077175100        0.33278000    -0.542456000   -0.545458000
95_1115    -0.246550000        0.30166700    -0.045651200    0.212230000
1_1116      0.163337000       -0.21220600     0.767262000    0.243419000
26_1144    -0.043306400       -0.34924900     0.052079500    0.550982000
89_1145    -0.097662100        0.36342700    -0.121072000   -0.435369000
19_1149    -0.419400000       -0.51282800    -0.455720000    0.463826000
47_1154    -0.468822000       -0.44291800    -0.068502700    0.440650000
78_1156    -0.268298000        0.26143300    -0.302509000   -0.286538000
71_1158     0.301012000        0.48948400    -0.045038500   -0.318457000
90_1161    -0.054478300        0.45445200    -0.606532000   -0.610089000
99_1165     0.101789000        0.35653900    -0.569872000   -0.527555000
83_1173    -0.061525600       -0.34178600    -0.011406100    0.533827000
73_1174    -0.061525600       -0.34178600    -0.011406100    0.533827000
11_1175    -0.047041200       -0.24577400     0.888841000    0.295631000
52_1184     0.437920000        0.46011400     0.099817900   -0.313152000
48_1189    -0.159039000       -0.48363700     0.003205570    0.263206000
17_1198     0.141092000       -0.14927300     0.811179000    0.531098000
69_1203    -0.268298000        0.26143300    -0.302509000   -0.286538000
57_1204    -0.167242000       -0.39324800     0.167223000    0.232506000
19_1209     0.193896000       -0.25905200    -0.065438900    0.028426400
2_1217      0.048872000       -0.32298400     0.541136000    0.174835000
38_1218     0.017144700       -0.24697700    -0.097168200    0.033888100
67_1220    -0.676326000        0.08662870    -0.470671000    0.218813000
66_1229    -0.254289000       -0.34472900     0.091708000    0.142962000
92_1230     0.160247000        0.38640000     0.002166150    0.101997000
79_1239    -0.252566000        0.22194000    -0.470438000   -0.219733000
71_1241     0.041810000        0.33443100     0.040716400   -0.454037000
42_1248     0.406505000        0.41475100     0.034619000   -0.373919000
52_1249     0.300366000        0.47037300     0.051449800   -0.350752000
70_1252    -0.132057000        0.39616600    -0.218018000   -0.274477000
65_1264    -0.145650000       -0.40693600     0.121968000    0.283342000
96_1267    -0.374084000        0.20322000    -0.393735000    0.016209600
91_1272     0.191519000        0.39238500    -0.038286000   -0.337097000
67_1273    -0.676326000        0.08662870    -0.470671000    0.218813000
38_1293     0.017144700       -0.24697700    -0.097168200    0.033888100
46_1294    -0.077132700       -0.37337700     0.065524800    0.229309000
7_1299      0.129992000       -0.26790900     0.875185000    0.492204000
55_1312     0.038080900       -0.35771700     0.167806000    0.198673000
34_1339     0.233554000       -0.19104500    -0.054761600   -0.160458000
15_1346     0.474154000       -0.30234400     0.437676000    0.006438880
18_1351    -0.090352300       -0.39198000     0.620436000    0.479399000
97_1356    -0.257065000        0.28790800    -0.240731000   -0.008861840
54_1369     0.199531000       -0.36133700     0.170674000    0.085399400
75_1373    -0.124059000       -0.42062500     0.076713700    0.334177000
92_1376    -0.067640000       -0.33013000     0.167042000    0.377171000
86_1381    -0.334710000        0.09164390    -0.103253000    0.142097000
64_1398    -0.124059000       -0.42062500     0.076713700    0.334177000
89_1400    -0.097662100        0.36342700    -0.121072000   -0.435369000
40_1414    -0.275735000        0.13343600    -0.280951000    0.066933500
48_1417    -0.245717000       -0.46821700     0.043123800    0.159906000
58_1431    -0.676326000        0.08662870    -0.470671000    0.218813000
18_1437    -0.422914000       -0.48544400     0.351675000    0.356068000
100_1438    0.027444500        0.36707600    -0.581301000   -0.512264000
19_1440     0.193896000       -0.25905200    -0.065438900    0.028426400
16_1447     0.007689390       -0.42923500     0.152797000    0.372610000
84_1448    -0.254163000       -0.42107700    -0.025520500    0.399627000
58_1454    -0.504510000        0.16144000    -0.519748000    0.132224000
41_1456    -0.066260600        0.30696100    -0.150939000   -0.521849000
30_1458    -0.456489000       -0.06604580    -0.341581000    0.132091000
93_1459     0.034403800       -0.41471000     0.266883000    0.551112000
28_1472    -0.281401000       -0.28698600    -0.181593000    0.487920000
62_1479     0.437920000        0.46011400     0.099817900   -0.313152000
16_1489     0.418563000       -0.23646500     0.280498000    0.205337000
72_1496     0.244952000        0.37021900     0.155761000   -0.113251000
96_1502    -0.006250590        0.41762600    -0.260804000   -0.257251000
56_1514    -0.167242000       -0.39324800     0.167223000    0.232506000
22_1519     0.314260000       -0.29617200     0.238027000   -0.217692000
2_1521      0.163337000       -0.21220600     0.767262000    0.243419000
32_1528    -0.032176400       -0.32368800    -0.053932700   -0.270325000
45_1552     0.083948900       -0.40435000     0.300151000    0.190925000
83_1554     0.025844500       -0.38413400     0.133275000    0.444203000
87_1557    -0.540735000        0.12084800    -0.609589000   -0.075789200
76_1566    -0.229822000       -0.29911000     0.093101800    0.060770600
60_1568    -0.346749000        0.25369700    -0.289751000   -0.159530000
28_1581    -0.463824000       -0.44342200    -0.150505000    0.519466000
43_1608     0.422212000        0.43743300     0.067218400   -0.343535000
53_1625     0.321043000        0.47444800     0.165565000   -0.177605000
76_1633     0.021954100       -0.44763700     0.205162000    0.137351000
55_1649     0.408877000       -0.01830100     0.256985000    0.175018000
40_1650    -0.301373000        0.20441500    -0.332080000   -0.023280200
88_1677    -0.268298000        0.26143300    -0.302509000   -0.286538000
20_1682    -0.456489000       -0.06604580    -0.341581000    0.132091000
25_1689     0.588573000       -0.30988500     0.511616000    0.183525000
24_1702     0.817941000        0.57826200     0.302552000   -0.568406000
63_1715     0.123314000       -0.13586000     0.315439000    0.326621000
2_1720      0.163337000       -0.21220600     0.767262000    0.243419000
32_1748    -0.032176400       -0.32368800    -0.053932700   -0.270325000
9_1762     -0.247512000       -0.40421000     0.655439000    0.398094000
34_1789     0.240929000       -0.25052900    -0.065547200   -0.080013000
4_1790      0.376920000       -0.32242500     0.008467910   -0.370943000
45_1825     0.591660000       -0.18232800     0.136351000   -0.152810000
51_1829     0.217496000        0.46818200    -0.014469900   -0.498731000
24_1844     0.388472000        0.30341900     0.151238000   -0.278790000
27_1852    -0.006899620       -0.34855800     0.240138000    0.600715000
54_1853     0.488650000       -0.32853100     0.122850000   -0.031346000
2_1858      0.050910900       -0.26377500     0.668960000    0.230572000
35_1865     0.199531000       -0.36133700     0.170674000    0.085399400
3_1868     -0.044572800       -0.31632900     0.694704000    0.134589000
46_1873    -0.130767000       -0.39121500     0.114193000    0.387924000
41_1885     0.292656000        0.30374300    -0.006480190   -0.425352000
84_1904    -0.274081000       -0.42833200    -0.012880000    0.221058000
49_1905    -0.582723000        0.14046600    -0.368673000    0.034404800
17_1909     0.006975600       -0.30738900     0.149001000    0.520799000
87_1931    -0.572199000        0.19983400    -0.273732000   -0.209401000
35_1932     0.689504000       -0.22592500     0.516583000    0.279807000
52_1933     0.329011000        0.46528200     0.062439000   -0.491378000
84_1936    -0.254163000       -0.42107700    -0.025520500    0.399627000
7_1939      0.118892000       -0.38654400     0.939190000    0.453309000
73_1953    -0.017978600       -0.32175500     0.004667400    0.551564000
89_1962    -0.054478300        0.45445200    -0.606532000   -0.610089000
66_1964    -0.257165000       -0.40403700     0.045059500    0.275989000
33_1965     0.406505000        0.41475100     0.034619000   -0.373919000
55_1966    -0.025238900       -0.44720600     0.109615000    0.186214000
99_1973     0.004601070        0.36043100    -0.530996000   -0.513394000
50_1982    -0.092395300        0.28494100    -0.178789000   -0.214266000
77_2010    -0.469948000        0.25817700    -0.512739000   -0.230230000
97_2025    -0.204721000        0.43989300    -0.168366000   -0.152636000
10_2031    -0.244746000        0.02632180     0.309231000    0.266904000
56_2053    -0.012457900       -0.37351100     0.098727300    0.135013000
100_2063   -0.073385900        0.29436000    -0.535556000   -0.488900000
26_2072    -0.011783100       -0.42930700     0.102912000    0.545963000
90_2077    -0.054478300        0.45445200    -0.606532000   -0.610089000
20_2079    -0.380303000        0.12492000     0.055789400    0.165171000
65_2090     0.065826500       -0.40848500     0.202876000    0.216792000
12_2101    -0.163431000       -0.30819900     0.662204000    0.219046000
53_2104     0.321043000        0.47444800     0.165565000   -0.177605000
17_2119     0.179986000       -0.24549900     0.214566000    0.589948000
94_2124    -0.161239000       -0.42732700     0.026063000    0.479783000
66_2127    -0.201075000       -0.44183800     0.051344200    0.122645000
85_2135    -0.118308000       -0.30201000     0.170011000    0.068123600
60_2141    -0.577704000        0.28057600    -0.304015000   -0.177102000
40_2145    -0.225883000        0.20519200    -0.280371000    0.031024100

In [12]:
pd.read_table('/work/lotterhos/brandon/continuous_space_runtime/fitness_mats/tutorial_1.txt')

,25_33,85_34,57_44,31_45,11_46,22_64,47_65,10_72,20_85,64_106,100_119,76_127,11_132,23_164,18_173,29_175,49_194,67_198,6_207,61_215,22_216,47_221,29_224,22_230,9_236,67_254,52_255,64_261,30_268,42_269,1_271,96_280,84_293,19_306,78_309,77_314,34_338,92_348,66_352,63_359,66_382,79_385,40_386,51_397,50_404,36_405,15_412,16_423,26_437,54_438,...,83_8163,7_8169,1_8172,75_8187,33_8217,43_8222,95_8228,40_8229,23_8231,23_8242,97_8252,76_8286,15_8311,64_8326,91_8330,79_8346,12_8351,93_8359,39_8360,62_8367,73_8371,24_8392,98_8394,39_8402,84_8409,75_8417,97_8418,59_8432,43_8446,3_8456,47_8458,99_8462,37_8468,60_8484,58_8500,32_8503,39_8509,45_8516,48_8533,57_8534,55_8535,63_8536,26_8547,45_8559,68_8564,22_8575,75_8580,62_8582,79_8585,78_8590
1,0.51512,0.629394,0.391132,0.445775,0.914052,0.653387,0.646495,0.6926,0.541038,0.754496,0.339901,0.444621,0.695847,0.519039,0.828569,0.493857,0.46052,0.686715,0.645799,0.49265,0.655309,0.773413,0.530306,0.655309,0.828569,0.46634,0.4805,0.765004,0.508249,0.41053,0.988822,0.545878,0.649216,0.474823,0.394692,0.431491,0.541283,0.578675,0.632584,0.69827,0.632584,0.478368,0.472253,0.436936,0.472253,0.820122,0.570782,0.799936,0.80355,0.665105,...,0.642307,0.845942,0.974128,0.615396,0.471031,0.499594,0.707139,0.666928,0.496706,0.477771,0.459048,0.630283,0.642003,0.761429,0.552331,0.402566,0.811028,0.641666,0.46052,0.584532,0.705264,0.383429,0.485955,0.438077,0.649216,0.615396,0.451184,0.356118,0.534473,0.809931,0.867853,0.472843,0.589207,0.520398,0.391132,0.521896,0.493857,0.613319,0.775248,0.535861,0.77843,0.784841,0.842294,0.746161,0.391132,0.491407,0.700836,0.541927,0.348332,0.413359

In [13]:
len(fs(fitness_dir))

100

In [14]:
f = fs(fitness_dir)[0]

!ls -l $f

-rw-r--r-- 1 b.lind users 27719 Dec  4 12:34 /work/lotterhos/brandon/continuous_space_runtime/fitness_mats/tutorial_1.txt

In [15]:
!date

Wed Dec  4 12:40:44 EST 2024

In [16]:
formatclock(dt.now() - t0)

'0-00:00:07'